version: '3.0'

services:
  db:
    image: mysql:8.0.11
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - C:/Users/s2022/Documents/Study/cosmos/dev/db:/var/lib/mysql
