datasource:
  url: jdbc:h2:mem:testdb

spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    display-request-duration: true
  paths-to-match:
    - /**
